language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
branches:
  except:
    - "master"
script:
 - npm run test
# TODO: Define coverage strategy here after testing build with no env and external PR
cache:
  directories:
  - node_modules
