hyper-deploy-steps: &hyper-deploy-steps
  - attach_workspace:
      at: ~/circleci-deployment
  - run:
      name: Install hyper
      command: |
        wget https://hyper-install.s3.amazonaws.com/hyper-linux-x86_64.tar.gz
        tar xzf hyper-linux-x86_64.tar.gz
        chmod +x hyper
        ./hyper --help
  - run:
      name: Build Docker
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build -f docker/Dockerfile -t bespoken/bst:$CIRCLE_TAG .
        docker push bespoken/bst:$CIRCLE_TAG
  - run:
      name: Login to Hyper
      command: |
        ./hyper config --accesskey $HYPER_KEY --secretkey $HYPER_SECRET --default-region us-west-1
        ./hyper login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        ./hyper pull bespoken/bst:$CIRCLE_TAG
  - run:
      name: Deploy container
      command: |
        if [ "$TYPE_OF_DEPLOY" == "server" ]; then
          ./hyper rm -f bst || true
          >
            ./hyper run
            -e AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            -e AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            -e SSL_CERT="$SSL_CERT"
            -e SSL_KEY="$SSL_KEY"
            -e SOURCE_API_URL="$SOURCE_API_URL_PROD"
            -d
            --name bst
            --size s4
            --restart=always
            -P bespoken/bst:$CIRCLE_TAG
          ./hyper fip attach -f 199.245.58.242 bst
        else
          ./hyper rm -f bst-dev || true
          >
            ./hyper run
            -e AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            -e AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            -e SSL_CERT="$SSL_CERT"
            -e SSL_KEY="$SSL_KEY"
            -e SOURCE_API_URL="$SOURCE_API_URL_DEV"
            -d
            --name bst-dev
            --size s4
            --restart=always
            -P bespoken/bst:$CIRCLE_TAG
          ./hyper fip attach -f 199.245.58.199 bst-dev
        fi

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: .

  codecov:
    machine: true
    environment:
      - SKIP_STATISTICS: "true"
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: npm run codecov
      - persist_to_workspace:
          root: .
          paths: .
  bst-dev:
    machine: true
    environment:
      - TYPE_OF_DEPLOY: dev
      - SKIP_STATISTICS: "true"

    working_directory: ~/circleci-deployment
    steps: *hyper-deploy-steps

  bst-server:
    machine: true
    environment:
      - TYPE_OF_DEPLOY: server
      - SKIP_STATISTICS: "true"

    working_directory: ~/circleci-deployment
    steps: *hyper-deploy-steps


workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - bst-test
      - codecov:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - bst-test
      - bst-dev:
          requires:
            - test
          filters:
            tags:
              only: /bst-dev-.*/
            branches:
              ignore: /.*/
      - bst-server:
          requires:
            - test
          filters:
            tags:
              only: /bst-server-.*/
            branches:
              ignore: /.*/