deploy-steps: &deploy-steps
  - attach_workspace:
      at: ~/circleci-deployment
  - run:
      name: Build Docker
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build -f docker/Dockerfile -t bespoken/bst:$CIRCLE_TAG .
        docker push bespoken/bst:$CIRCLE_TAG
  - run:
      name: Deploy container
      command: |
        echo -e $EC2_SSL_KEY > bst-server.pem
        chmod 400 bst-server.pem
        ssh -i bst-server.pem $BST_CONTAINER "
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker pull bespoken/bst:$CIRCLE_TAG
        docker stop \$(docker ps -aq)
        docker run -d --env-file .env -p 443:443 -p 5000:5000 -p 80:80 bespoken/bst:$CIRCLE_TAG
        "

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - checkout
      - run: npm install
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: .

  codecov:
    machine: true
    environment:
      - SKIP_STATISTICS: "true"
    working_directory: ~/circleci-deployment
    steps:
      - attach_workspace:
          at: ~/circleci-deployment
      - run: npm run codecov
      - persist_to_workspace:
          root: .
          paths: .
  bst-dev:
    machine: true
    environment:
      - TYPE_OF_DEPLOY: dev
      - SKIP_STATISTICS: "true"
      - BST_CONTAINER: ec2-user@ec2-35-153-68-76.compute-1.amazonaws.com
    working_directory: ~/circleci-deployment
    steps: *deploy-steps

  bst-server:
    machine: true
    environment:
      - TYPE_OF_DEPLOY: server
      - BST_CONTAINER: ec2-user@ec2-18-232-68-210.compute-1.amazonaws.com
    working_directory: ~/circleci-deployment
    steps: *deploy-steps
  
  skill-testing-release:
    docker:
      - image: circleci/node:8
    environment:
      - ASK_ACCESS_TOKEN: dummy
      - ASK_REFRESH_TOKEN: dummy
      - ASK_VENDOR_ID: dummy
      - ASK_SKILL_ID: dummy
      - VIRTUAL_DEVICE_TOKEN: dummy
    working_directory: ~/skill-testing-release
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:77:b3:3a:08:72:b8:ad:bf:c4:11:97:3b:18:85:76"
      - checkout
      - run: git config --global user.email "$GITHUB_USER_EMAIL_RELEASE"
      - run: git config --global user.name "$GITHUB_USER_NAME_RELEASE"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: git clone git@github.com:bespoken/skill-testing-ml.git
      - run: cd skill-testing-ml && npm install
      - run: cd skill-testing-ml && npm --no-git-tag-version version patch
      - run:
          name: get version
          command: |
            cd skill-testing-ml
            SKILL_TESTING_VERSION=$(node -pe "require('./package.json').version")
            echo "export VERSION=$SKILL_TESTING_VERSION" >> $BASH_ENV
      - run: mkdir -p workspace
      - run: echo "export SKILL_TESTING_VERSION=$VERSION" >> workspace/new-env-vars
      - run: echo $VERSION
      - run: cd skill-testing-ml && git add package.json package-lock.json docs/*
      - run:
          name: commit changes
          command: |
            cd skill-testing-ml
            git commit -m "Version $VERSION" -m "* $VERSION
            * update docs"
      - run: cd skill-testing-ml && git tag $VERSION
      - run: cd skill-testing-ml && git tag -l
      - run: cd skill-testing-ml && git push && git push --tags
      - run: cd skill-testing-ml && npm publish --tag beta
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars

  bst-client-release:
    docker:
      - image: circleci/node:8
    working_directory: ~/bst-client-release
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:77:b3:3a:08:72:b8:ad:bf:c4:11:97:3b:18:85:76"
      - checkout
      - attach_workspace:
          at: ~/bst-client-release/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo $SKILL_TESTING_VERSION
      - run: git config --global user.email "$GITHUB_USER_EMAIL_RELEASE"
      - run: git config --global user.name "$GITHUB_USER_NAME_RELEASE"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm install
      - run: git checkout .
      - run: git checkout master
      - run:
          name: update skill testing ref
          command: |
            REPLACE_PATTERN="s/\"skill-testing-ml\": \".*\"/\"skill-testing-ml\": \"~$SKILL_TESTING_VERSION\"/g"
            sed -i -e "$REPLACE_PATTERN" package.json
            git add package.json
            git diff-index --quiet HEAD || git commit -m "update skill testing ref"
      - run: npm version patch
      - run: git push && git push --tags
      - run: npm publish --tag beta
workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - codecov:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - bst-dev:
          requires:
            - test
          filters:
            tags:
              only: /bst-dev-.*/
            branches:
              ignore: /.*/
      - bst-server:
          requires:
            - test
          filters:
            tags:
              only: /bst-server-.*/
            branches:
              ignore: /.*/
      - skill-testing-release:
          requires:
            - test
          filters:
            tags:
              only: /bst-client-.*/
            branches:
              ignore: /.*/
      - bst-client-release:
          requires:
            - skill-testing-release
          filters:
            tags:
              only: /bst-client-.*/
            branches:
              ignore: /.*/